### ISSUE TITLE
"Issueベース開発"レビュー依頼

### ISSUE THREAD

**Issue by Ryosei0628** [Ryosei0628/zenfocus#2]
### 概要
MVPリリースまでの実装予定の内容です
現状ストーリーポイント54×2=108時間
GitHubProjectをpublic設定済みです
### 実装内容予定の機能

- ユーザー登録機能

- ログイン・ログアウト機能

- 投稿一覧機能（カード）

- 投稿一覧機能（Gppgle Maps APIを使用した地図）

- 新規投稿機能

- 画像投稿機能

- 投稿詳細機能

- 投稿編集機能

- 投稿削除機能

- ransackを使った検索機能　（タイトル、本文、ジャンル）

必要なページ

- トップページ

- ヘッダー（ログイン前）

- ヘッダー（ログイン後）

- フッター

- 投稿一覧画面（カード）

- 投稿一覧画面（地図）

- 新規投稿画面

- 投稿詳細画面

- 地図上でピンをクリックした際の投稿詳細画面の一部

- 投稿編集画面

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/15949129-f2f6-496f-bb9e-a8b5bb4d4114)

対応ありがとうございます。
Projectsページにアクセスしましたが、看板・issue・ストーリーポイントが確認できませんでした。
カリキュラムをご確認いただいて、レビューワー側で上記が確認できるように対応いただき、再提出操作をお願いいたします。

**Comment by Ryosei0628** [comment]
こちらで確認できるように調整しました。ご確認よろしくお願いします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
