### ISSUE TITLE
MVPリリースのレビュー依頼

### ISSUE THREAD

**Issue by Ryosei0628** [Ryosei0628/zenfocus#77]
##  各種情報

サービス名: zenfocus
サービスURL: https://zenfocus.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能

-  ユーザー認証機能 　 　
  - [ ] ユーザー登録 　 　
  - [ ] ログイン/ログアウト 　 　
  - [ ] パスワードリセット
- 場所の投稿 　 　
  - [ ] 投稿フォーム
  - [ ]  写真のアップロード   　 　
- [ ] 地図で場所を表示 　 　
- [ ] 検索用タグの実装
- [ ] レビュー機能 　 　
- [ ] ユーザーによるコメントやレビュー機能

### 開発途中でMVPリリース時点で作らなくなった機能

- [ ] パスワードリセット機能
- [ ] 検索用のタグの実装（本リリースでも作成しない→代わりにジャンル検索を実装予定）
- [ ] レビュー機能
- [ ] ユーザーによるコメント機能

## サービスイメージがわかるようなスクリーンショット等

<トップ画面>

![Image](https://github.com/user-attachments/assets/5b825bc3-847f-4547-860a-6dcb9b6e91a5)

<ユーザー登録画面>
![Image](https://github.com/user-attachments/assets/31d82174-f288-4101-a5dc-17e93df55b25)

<ログイン画面>

![Image](https://github.com/user-attachments/assets/3be0c545-2ab8-4b14-b117-8f3bc7e40329)

<投稿フォーム>
![Image](https://github.com/user-attachments/assets/5bbfa9a2-dfc4-4802-a1fa-767fa46324eb)

<投稿一覧画面>
![Image](https://github.com/user-attachments/assets/7c40c7d0-9cda-473f-8596-eb10baed8a00)
＊テストのため投稿内容は実際のものとは関係ありません。

<投稿一覧画面(地図)>
![Image](https://github.com/user-attachments/assets/8942ea84-a32d-4996-96cf-4da586052a11)

本リリースで、一覧画面&地図一覧画面に検索機能を実装予定です。

**Comment by tmtkzk0823** [comment]
MVPを満たす機能ができていると思います！
LGTMです！
